"""Add Meter Table

Revision ID: 6d48d9633a98
Revises: 94c4fe3dcde4
Create Date: 2024-01-28 20:37:32.372460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d48d9633a98'
down_revision = '94c4fe3dcde4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_type', sa.String(length=255), nullable=False),
    sa.Column('meter_number', sa.String(length=255), nullable=False),
    sa.Column('meter_status', sa.String(length=255), nullable=False),
    sa.Column('meter_created_at', sa.DateTime(), nullable=True),
    sa.Column('meter_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meters')
    # ### end Alembic commands ###
